### ISSUE TITLE
Fatal error on php bin/cli sync

### ISSUE THREAD

**Issue by stopz** [sitelease/acappella#3]
Just made a fresh install via composer and went trough installation steps in the readme.md, everything successful and flawless until php bin/cli sync

{code}
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: You have requested a non-existent parameter "gitea.pushEventSecret". in /vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php:54

Stack trace:
#0 /vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(82): Symfony\Component\DependencyInjection\Compiler\DefinitionErrorExceptionPass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#1 /vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php(32): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#2 /vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(46): Symfony\Component\DependencyInjection\Compiler\Definition in vendor/symfony/dependency-injection/Compiler/DefinitionErrorExceptionPass.php on line 54
{/code}

I get the exact same output when i visit index from the browser. Updating packages aint helping :)

Any quick fix ides? Hope this helps, this app and it's idea is gold!

**Comment by aKalisch** [comment]
Same here.
